# Generated by Django 6.0.6 on 2026-06-29 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credits', models.PositiveIntegerField()),
                ('price_idr', models.PositiveIntegerField(help_text='Harga dalam Rupiah.')),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'credits'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text="e.g. 'mock' or 'mayar'", max_length=30)),
                ('provider_ref', models.CharField(blank=True, help_text='Reference id at the provider.', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('paid', 'Berhasil'), ('failed', 'Gagal'), ('expired', 'Kadaluarsa')], default='pending', max_length=20)),
                ('amount_idr', models.PositiveIntegerField()),
                ('credits_granted', models.PositiveIntegerField(default=0)),
                ('pay_url', models.URLField(blank=True, max_length=1000)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.creditpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
