# Generated by Django 6.0.6 on 2026-06-29 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_project_business_description_project_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('offerings', models.JSONField(blank=True, default=list)),
                ('themes', models.JSONField(blank=True, default=list)),
                ('target_audience', models.TextField(blank=True)),
                ('competitor_hints', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(default='id', max_length=10)),
                ('source_url', models.URLField(blank=True)),
                ('website_fetched', models.BooleanField(default=False)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Business analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
