# Generated by Django 6.0.6 on 2026-06-29 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_business_description_project_goal_and_more'),
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=30)),
                ('page_source', models.CharField(blank=True, max_length=500)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('difficulty', models.FloatField(blank=True, null=True)),
                ('cpc', models.FloatField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, max_length=30)),
                ('confidence', models.FloatField(default=0.5)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_keywords', to='projects.project')),
            ],
            options={
                'ordering': ['keyword'],
                'unique_together': {('project', 'keyword')},
            },
        ),
    ]
