# Generated by Django 6.0.6 on 2026-06-29 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_business_description_project_goal_and_more'),
        ('strategy', '0002_discoveredkeyword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discoveredkeyword',
            options={'ordering': ['-priority_score', 'keyword']},
        ),
        migrations.AddField(
            model_name='discoveredkeyword',
            name='business_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveredkeyword',
            name='priority_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='discoveredkeyword',
            name='search_intent',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='TopicCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('intent', models.CharField(blank=True, max_length=30)),
                ('priority', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='projects.project')),
            ],
            options={
                'ordering': ['-priority', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='discoveredkeyword',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keywords', to='strategy.topiccluster'),
        ),
    ]
