# Generated by Django 6.0.6 on 2026-06-29 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_business_description_project_goal_and_more'),
        ('queue_manager', '0003_queuejob_cost_image_usd_queuejob_cost_text_usd_and_more'),
        ('strategy', '0003_alter_discoveredkeyword_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_title', models.CharField(max_length=300)),
                ('alt_titles', models.JSONField(blank=True, default=list)),
                ('priority', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('generating', 'Generating'), ('generated', 'Generated'), ('published', 'Published'), ('failed', 'Failed')], default='planned', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='strategy.topiccluster')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='strategy.discoveredkeyword')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='projects.project')),
                ('queue_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_item', to='queue_manager.queuejob')),
            ],
            options={
                'ordering': ['-priority'],
                'unique_together': {('project', 'keyword')},
            },
        ),
    ]
