# Generated by Django 6.0.6 on 2026-06-29 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_business_description_project_goal_and_more'),
        ('strategy', '0004_contentplanitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(choices=[('ai', 'AI Campaign'), ('manual', 'Manual Import')], default='ai', max_length=10)),
                ('goal', models.CharField(blank=True, max_length=20)),
                ('target_country', models.CharField(default='ID', max_length=10)),
                ('language', models.CharField(default='id', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('building', 'Building'), ('plan_ready', 'Plan Ready'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('articles_per_day', models.PositiveIntegerField(default=3)),
                ('planned_count', models.IntegerField(default=0)),
                ('generated_count', models.IntegerField(default=0)),
                ('published_count', models.IntegerField(default=0)),
                ('total_cost_usd', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contentplanitem',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='strategy.campaign'),
        ),
    ]
