# Generated by Django 6.0.6 on 2026-06-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0005_campaign_contentplanitem_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='progress_step',
            field=models.CharField(blank=True, default='queued', max_length=20),
        ),
    ]
