# Generated by Django 6.0.6 on 2026-06-29 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
        ('strategy', '0006_campaign_progress_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentplanitem',
            name='content_brief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='research.contentbrief'),
        ),
    ]
