# Generated by Django 6.0.6 on 2026-06-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='daily_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 = tidak terbatas'),
        ),
        migrations.AddField(
            model_name='project',
            name='schedule_times',
            field=models.CharField(blank=True, help_text='Jam publish, pisahkan koma. Contoh: 08:00,13:00,20:00', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='threads_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
