# Generated by Django 6.0.6 on 2026-06-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_daily_limit_project_schedule_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='brand_voice',
            field=models.TextField(blank=True, help_text='Karakter/gaya brand yang harus tercermin di artikel.'),
        ),
        migrations.AddField(
            model_name='project',
            name='default_cta',
            field=models.CharField(blank=True, help_text='Call-to-action default di akhir artikel.', max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='default_length',
            field=models.PositiveIntegerField(choices=[(1000, '1000 kata'), (1500, '1500 kata'), (2000, '2000 kata'), (3000, '3000 kata'), (5000, '5000+ kata')], default=1500),
        ),
        migrations.AddField(
            model_name='project',
            name='writing_style',
            field=models.CharField(choices=[('blog', 'Blog'), ('review', 'Review'), ('tutorial', 'Tutorial'), ('listicle', 'Listicle'), ('evergreen', 'Evergreen'), ('news', 'News')], default='blog', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='tone',
            field=models.CharField(choices=[('formal', 'Formal'), ('professional', 'Profesional'), ('casual', 'Santai'), ('educational', 'Edukatif'), ('persuasive', 'Persuasif'), ('informative', 'Informatif')], default='informative', max_length=50),
        ),
    ]
