# Generated by Django 6.0.6 on 2026-06-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_brand_voice_project_default_cta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ai_model',
            field=models.CharField(blank=True, default='', help_text='Kosongkan untuk pakai default sistem (AI_DEFAULT_MODEL di .env).', max_length=100),
        ),
    ]
