# Generated by Django 6.0.6 on 2026-06-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='business_description',
            field=models.TextField(blank=True, help_text='Apa bisnisnya, produk/jasanya.'),
        ),
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.CharField(choices=[('traffic', 'Traffic organik'), ('leads', 'Leads'), ('affiliate', 'Affiliate'), ('ecommerce', 'Ecommerce'), ('awareness', 'Brand awareness')], default='traffic', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='niche',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='target_country',
            field=models.CharField(default='ID', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='website_url',
            field=models.URLField(blank=True, help_text='Opsional jika website baru.'),
        ),
    ]
