# Generated by Django 6.0.6 on 2026-06-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='threads_access_token',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='threads_user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
