# Generated by Django 6.0.6 on 2026-06-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuejob',
            name='auto_title',
            field=models.BooleanField(default=False),
        ),
    ]
