# Generated by Django 6.0.6 on 2026-06-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0002_queuejob_auto_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuejob',
            name='cost_image_usd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='queuejob',
            name='cost_text_usd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='queuejob',
            name='cost_total_usd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='queuejob',
            name='duration_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuejob',
            name='gen_fallback_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queuejob',
            name='model_used',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='queuejob',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='queuejob',
            name='quality_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queuejob',
            name='quality_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queuejob',
            name='revision_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuejob',
            name='tokens_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuejob',
            name='tokens_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuejob',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
