# Generated by Django 6.0.6 on 2026-06-29 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_project_brand_voice_project_default_cta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=300)),
                ('language', models.CharField(default='id', max_length=10)),
                ('search_intent', models.CharField(blank=True, max_length=50)),
                ('intent_note', models.TextField(blank=True)),
                ('competitors', models.JSONField(blank=True, default=list)),
                ('headings', models.JSONField(blank=True, default=list)),
                ('people_also_ask', models.JSONField(blank=True, default=list)),
                ('related_searches', models.JSONField(blank=True, default=list)),
                ('entities', models.JSONField(blank=True, default=list)),
                ('lsi_keywords', models.JSONField(blank=True, default=list)),
                ('faq', models.JSONField(blank=True, default=list)),
                ('content_gap', models.JSONField(blank=True, default=list)),
                ('recommended_word_count', models.PositiveIntegerField(default=0)),
                ('internal_link_opportunities', models.JSONField(blank=True, default=list)),
                ('external_reference_opportunities', models.JSONField(blank=True, default=list)),
                ('ai_overview_opportunity', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='briefs', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='briefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['keyword', 'language'], name='research_co_keyword_eb45a7_idx')],
            },
        ),
    ]
