# Generated by Django 6.0.6 on 2026-06-29 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_project_brand_voice_project_default_cta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500)),
                ('language', models.CharField(default='id', max_length=10)),
                ('gl', models.CharField(default='id', help_text='Google country (geo) code.', max_length=10)),
                ('provider', models.CharField(default='stub', help_text="SERP source, e.g. 'serper' or 'stub'.", max_length=50)),
                ('search_intent', models.CharField(blank=True, max_length=50)),
                ('ai_overview_present', models.BooleanField(blank=True, null=True)),
                ('median_word_count', models.IntegerField(default=0)),
                ('paa', models.JSONField(blank=True, default=list)),
                ('related_searches', models.JSONField(blank=True, default=list)),
                ('entities', models.JSONField(blank=True, default=list)),
                ('semantic_keywords', models.JSONField(blank=True, default=list)),
                ('subtopics', models.JSONField(blank=True, default=list)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('brief', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('url', models.URLField(max_length=1000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True)),
                ('h1', models.CharField(blank=True, max_length=500)),
                ('h2', models.JSONField(blank=True, default=list)),
                ('h3', models.JSONField(blank=True, default=list)),
                ('faq', models.JSONField(blank=True, default=list)),
                ('word_count', models.IntegerField(default=0)),
                ('schema_types', models.JSONField(blank=True, default=list)),
                ('image_alts', models.JSONField(blank=True, default=list)),
                ('internal_link_opps', models.JSONField(blank=True, default=list)),
                ('external_authority_opps', models.JSONField(blank=True, default=list)),
                ('publish_date', models.CharField(blank=True, max_length=100)),
                ('last_update', models.CharField(blank=True, max_length=100)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='research.researchsnapshot')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='researchsnapshot',
            index=models.Index(fields=['keyword', 'gl'], name='research_re_keyword_bbf554_idx'),
        ),
    ]
